- name: Create swap space
  command: dd if=/dev/zero of=/extraswap bs=1M count={{ swap_size }}
  when: ansible_swaptotal_mb < 1
  sudo: True

- name: Make swap
  command: mkswap /extraswap
  when: ansible_swaptotal_mb < 1
  sudo: True

- name: Add to fstab
  lineinfile: dest=/etc/fstab regexp="extraswap" line="/extraswap none swap sw 0 0" state=present
  when: ansible_swaptotal_mb < 1
  sudo: True
  notify: 
    - Turn swap on
    - Adjust swapiness

